"""Golden extraction corpus — messages from outside the demo domain.

The extractor was tuned on one web-dev script and passed its own tests while
extracting nothing from an ordinary sentence about a flight or a prescription.
Every case here is a message a real user might send, in a domain StateJar was
never demoed on, with the exact canonical paths it must produce.

`must` — paths that have to be present with these values.
`must_not` — paths that must NOT appear (the fragment and false-positive
             regressions, which are otherwise invisible in a coverage count).

Money is compared on its amount and dates on their ISO day; the envelope shape
is covered by test_canonical.py.
"""

from __future__ import annotations

# (name, message, must, must_not)
GOLDEN: list[tuple[str, str, dict, list[str]]] = [
    # --- e-commerce ------------------------------------------------------------
    ("ecom_basic",
     "Hi, I'm Meera from Nagpur. Order 3 t-shirts, budget under 1500, "
     "deliver by 20 September, contact me on whatsapp.",
     {"facts.name": "Meera", "facts.city": "Nagpur",
      "constraints.quantity": 3, "constraints.budget.max": 1500,
      "constraints.deadline": "-09-20", "preferences.contact_mode": "whatsapp"},
     []),
    ("ecom_payment",
     "payment method: UPI, delivery address: 12 MG Road, quantity 2",
     {"preferences.payment_method": "upi", "constraints.quantity": 2},
     []),
    # A currency marker is now required. "Nothing over 4999" states a ceiling
    # on an unnamed quantity — it could be rupees, grams or minutes — and
    # guessing rupees is the behaviour that put 24 tonnes in a budget field.
    ("ecom_price_cap",
     "Nothing over ₹4999 please, I'll pay by card",
     {"constraints.budget.max": 4999, "preferences.payment_method": "card"},
     []),
    ("ecom_bare_ceiling_declines",
     "Nothing over 4999 please",
     {},
     ["constraints.budget.max"]),
    ("ecom_return",
     "I need it before 15 August",
     {"constraints.deadline": "-08-15"},
     ["constraints.requirements"]),          # BUG-2

    # --- travel ---------------------------------------------------------------
    ("travel_route",
     "Book a flight from Pune to Goa on 15 Aug for 2 passengers, budget 8000",
     {"constraints.origin": "Pune", "constraints.destination": "Goa",
      "constraints.deadline": "-08-15", "constraints.quantity": 2,
      "constraints.budget.max": 8000},
     ["facts.city"]),                        # a route is not a home town
    ("travel_hotel",
     "my destination is Manali and my budget is 40k",
     {"constraints.destination": "Manali", "constraints.budget.max": 40000},
     []),
    ("travel_dates",
     "travelling next Friday, coming back in 2 weeks",
     {},                                     # relative dates resolve at runtime
     []),
    ("travel_prefs",
     "I prefer email for the itinerary, my name is Kabir Anand",
     {"preferences.contact_mode": "email", "facts.name": "Kabir Anand"},
     []),

    # --- healthcare intake ----------------------------------------------------
    ("health_intake",
     "Patient intake: age 34, allergies penicillin, symptoms fever",
     {"facts.age": 34, "constraints.allergies": ["penicillin"],
      "facts.symptoms": ["fever"]},
     []),
    ("health_meds",
     "my medications are metformin, my age is 58",
     {"facts.medications": ["metformin"], "facts.age": 58},
     []),
    ("health_appointment",
     "preferred time is 10am, please contact me by phone",
     {"preferences.time_slot": "10am", "preferences.contact_mode": "phone"},
     []),
    ("health_allergy_plural",
     "allergic to peanuts",
     {"constraints.allergies": ["peanuts"]},
     []),

    # --- job application ------------------------------------------------------
    ("job_basic",
     "Applying for the backend position. 5 years experience, skills Python",
     {"facts.experience_years": 5, "facts.skills": ["Python"]},
     []),
    ("job_org",
     "I currently work at Infosys, my role is senior engineer",
     {"facts.organization": "Infosys", "facts.role": "senior engineer"},
     []),
    ("job_notice",
     "my email is meera@example.com and my phone is 9876543210",
     {"facts.email": "meera@example.com", "facts.phone": "9876543210"},
     []),
    ("job_expectation",
     "expected package 18 lakh",
     {"constraints.budget.max": 1800000},
     []),

    # --- food ordering --------------------------------------------------------
    ("food_diet",
     "Order 2 pizzas, dietary vegetarian, payment method UPI",
     {"constraints.quantity": 2, "constraints.dietary": ["vegetarian"],
      "preferences.payment_method": "upi"},
     []),
    ("food_slot",
     "deliver by 8pm, my address is 44 Baner Road",
     {"facts.address": "44 Baner Road"},
     []),
    ("food_budget",
     "keep it under 600 rupees",
     {"constraints.budget.max": 600},
     []),
    ("food_cash",
     "cash on delivery please",
     {"preferences.payment_method": "cash"},
     []),

    # --- real estate ----------------------------------------------------------
    ("estate_bhk",
     "Looking for a 3 BHK, budget 90 lakh, area Koregaon Park",
     {"constraints.bedrooms": 3, "constraints.budget.max": 9000000,
      "constraints.area": "Koregaon Park"},
     []),
    ("estate_rent",
     "rent budget is 35000 a month, 2 bedrooms",
     {"constraints.budget.max": 35000, "constraints.bedrooms": 2},
     []),
    ("estate_contact",
     "reach me on whatsapp, I'm based in Mumbai",
     {"preferences.contact_mode": "whatsapp", "facts.city": "Mumbai"},
     []),

    # --- the original web-dev domain must not regress -------------------------
    ("webdev_brief",
     "Build a landing page. Stack is Next.js, brand colour #FF5A1F, "
     "target audience is small business owners, no external UI libraries.",
     {"decisions.stack": "Next.js", "preferences.brand_color": "#FF5A1F",
      "facts.audience": "small business owners"},
     []),
    ("webdev_theme",
     "my theme is dark",
     {"preferences.theme": "dark"},
     []),
    ("webdev_spec",
     "hi i am yashraj , i am from pune, i have 3000rs rupee , i prefer email",
     {"facts.name": "Yashraj", "facts.city": "Pune",
      "constraints.budget.max": 3000, "preferences.contact_mode": "email"},
     []),

    # --- messy: typos, Hinglish, density, contradiction -----------------------
    ("messy_hinglish",
     "mera naam Rohan hai Delhi se, budget 2000 se zyada nahi",
     {"facts.name": "Rohan", "facts.city": "Delhi",
      "constraints.budget.max": 2000},
     []),
    ("messy_hinglish_two",
     "main Priya hoon, 1.5 lakh tak ka budget, ASUS lunga",
     {"facts.name": "Priya", "constraints.budget.max": 150000,
      "decisions.choice": "ASUS"},
     []),
    ("messy_dense",
     "name Aarav, city Pune, budget 40k, prefer whatsapp, deadline 15 Aug, "
     "quantity 4",
     {"facts.name": "Aarav", "facts.city": "Pune",
      "constraints.budget.max": 40000, "preferences.contact_mode": "whatsapp",
      "constraints.deadline": "-08-15", "constraints.quantity": 4},
     []),
    ("messy_contradiction_in_one_message",
     "call me instead of email",
     {"preferences.contact_mode": "phone"},
     []),
    ("messy_greeting_only",
     "hi hello there",
     {},
     ["facts.name", "facts.city"]),
    ("messy_pronouns",
     "can you do that thing for me before then",
     {},
     ["constraints.requirements", "facts.name", "goals.primary"]),
    ("messy_numbers_not_money",
     "I need at least 16GB RAM and 3 sessions",
     {},
     ["constraints.budget.max"]),
    ("messy_units",
     "the file is 250 MB and the timeout is 30 seconds",
     {},
     ["constraints.budget.max", "facts.age"]),
    ("messy_email_in_prose",
     "you can write to me at kabir@example.com any time",
     {},
     ["facts.name"]),
    ("messy_case",
     "MY NAME IS SANJANA AND MY BUDGET IS 5000",
     {"facts.name": "Sanjana", "constraints.budget.max": 5000},
     []),
    ("messy_trailing_punct",
     "my city is Jaipur!!!",
     {"facts.city": "Jaipur"},
     []),
    ("messy_multiline",
     "name: Farhan\nbudget: 12000\ncontact: sms",
     {"facts.name": "Farhan", "constraints.budget.max": 12000,
      "preferences.contact_mode": "sms"},
     []),
    ("messy_emoji",
     "budget is 5000 🙏 prefer whatsapp 📱",
     {"constraints.budget.max": 5000, "preferences.contact_mode": "whatsapp"},
     []),
    ("messy_question",
     "what is my budget?",
     {},
     ["constraints.budget.max"]),            # a question states nothing
    ("messy_negation",
     "I don't have a budget yet",
     {},
     []),
    ("messy_long_ramble",
     "so i was wondering whether the thing we discussed the other day is "
     "still something you would be able to help me out with at all, because "
     "it has been a while and i am not sure where we landed",
     {},
     ["facts.name", "constraints.requirements", "goals.primary"]),
    ("messy_two_dates",
     "ship it by Friday and the review is on 12 March",
     {},
     []),
    ("messy_currency_symbol",
     "₹1,50,000 is my ceiling",
     {"constraints.budget.max": 150000},
     []),
    ("messy_spelled_money",
     "my budget is seventy five thousand",
     {"constraints.budget.max": 75000},
     []),
    ("messy_iso_date",
     "deadline is 2026-08-15",
     {"constraints.deadline": "2026-08-15"},
     []),
    ("messy_year_stated",
     "I need it before 15 Aug 2026",
     {"constraints.deadline": "2026-08-15"},
     ["constraints.requirements"]),
]
